spring:
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:liquibase/ChangeLog.yml
    drop-first: true
    password:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    user: sa