application:
  upload-path: uploads/
  jwt-expirationMs: 86400000
  jwt-secret: SimplegramSecretKey
  image-generator: https://api.multiavatar.com

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: qwerty3
  jpa:
      hibernate:
        ddl-auto: validate
        #ddl-auto: create
  liquibase:
    enabled: true
    change-log: classpath:liquibase/ChangeLog.yml